from typing import Tuple, List, Optional, Any, Dict

import numpy as np
from PIL import Image
from pathlib import Path

from utils import PathLike


class CCImage:
    """
    Helper class for loading train and val data.
    """
    def __init__(self, img_path: PathLike, mask_path: Optional[PathLike] = None, weights_path: Optional[PathLike] = None) -> None:
        """
        :param img_path: path to the image.
        :param mask_path: path to the mask, can be None for the autogenerated weights.
        :param weights_path: path to the weights, can be None for the autogenerated weights.
        """
        self._img_path = Path(img_path)
        self._mask_path = Path(mask_path) if mask_path is not None else None
        self._weights_path = Path(weights_path) if weights_path is not None else None
        self._name = self._img_path.name

    @property
    def name(self):
        """ Name of the image. """
        return self._name

    # TODO: separate img and mask getter?
    def as_tuple(self) -> Tuple[np.ndarray, ...]:
        """ Return images (source, mask, weights) as numpy array. """
        return self._load()

    def as_dict(self) -> Dict[str, Any]:
        img, gt, weights = self.as_tuple()
        return {"image": img, "gt": gt, "weights": weights}

    def _load(self) -> Tuple[np.ndarray, ...]:
        # TODO: how to handle RGB and grayscale images? currently hardcoded for grayscale
        img = (np.array(Image.open(str(self._img_path)).convert('L')) / 255.0).astype(np.float32)
        img = img[..., np.newaxis]

        if self._mask_path is not None:
            mask = np.array(Image.open(str(self._mask_path)).convert("L"), dtype=np.float32) / 255
        else:
            mask = np.zeros(img.shape[:-1], dtype=img.dtype)

        if self._weights_path is not None:
            weights = np.array(Image.open(str(self._weights_path)).convert("F"), dtype=np.float32)
        else:
            # by default weight mask whole image TODO: maybe just mask image with cluster size slightly increased?
            weights = np.ones(img.shape[:-1], dtype=img.dtype)

        return img, mask, weights
